Module 12 Case study 1

Efficient path using reinforcement learning

In [3]:
import numpy as np

In [4]:
locations = ['a','b','c','d','e']
num_locations = len(locations)

In [26]:
# distance among each of the location 

distance_matrix = np.array([
[0,3,20,7,18],
[3,0,5,8,12],
[20,5,0,4,8],
[7,8,4,0,6],
[18,12,8,6,0]
]
)

In [34]:
# Q-learning algorithm
# Q-learning parameters

alpha = 0.1
gamma = 0.9
epsilon = 0.2
episodes = 1000

# Q-table initialization

Q_table = np.zeros((num_locations, num_locations))
Q_table

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
# training 

for episode in range(episodes):
    current_location = np.random.randint(0, num_locations)
    while True:
        if np.random.uniform(0,1) < epsilon:      # exploration
            next_location = np.random.randint(0, num_locations)
        else:                                     # exploitation
            next_location = np.argmax(Q_table[current_location])

        reward = -distance_matrix[current_location, next_location]

        Q_table[current_location, next_location] += alpha * (reward+gamma * np.max(Q_table[next_location] - Q_table[current_location, next_location]))
        
        if next_location == current_location:
            break
        current_location = next_location

In [37]:
# optimal path from current to destination

def find_optimal_path(start, destination):
    path = [start]
    current = start
    while current != destination:
        next_location = np.argmax(Q_table[current])
        if next_location == current_location or next_location in path:
            break
        path.append(next_location)
        current = next_location
    if path[-1] != destination:
        path.append(destination)
    return [locations[i] for i in path]

current_location = input("Enter start location (a,b,c,d,e): ").strip().lower()
destination = input("Enter destination (a,b,c,d,e): ").strip().lower()

if current_location in locations and destination in locations:
    start_idx = locations.index(current_location)
    dest_idx = locations.index(destination)
    optimal_path = find_optimal_path(start_idx, dest_idx)
    print(f"Optimal path from {current_location} to {destination}: {'->'.join(optimal_path)}")
else:
    print('Try a different location')

Optimal path from a to e: a->e


In [38]:
print(Q_table)

[[  0.          -2.15210444 -12.71267111  -4.74898575  -9.66477961]
 [ -2.35515769   0.          -3.39213268  -5.08506844  -9.77277398]
 [-15.70105125  -4.32701422   0.          -3.25759133  -2.7933368 ]
 [ -5.49536794  -5.08506844  -3.25759133   0.          -4.71031538]
 [-12.91262665  -7.06329963  -4.70886642  -3.2215932    0.        ]]
